parameters:
  - name: 'appType'
    displayName: 'Application Type'
    type: string
    values:
      - Services
      - Web
  - name: 'projectName'
    displayName: 'Project Name'
    type: string
    values:
      - NavaIT.Dictionary.App
      - NavaIT.Dictionary.Web

stages:
  - template: 'build.yaml'
    parameters:
      buildConfiguration: 'Release'
      projectName: '**/${{parameters.projectName}}.csproj'
      artifact: '${{parameters.appType}}App'
  - stage: 'Deploy${{parameters.projectName}}'
    displayName: 'Deploy ${{parameters.projectName}}'
    jobs:
    - template: 'deploy.yaml'
      parameters:
        appType: ${{parameters.appType}}
        buildConfiguration: 'Release'
        projectName: '**/${{parameters.projectName}}.csproj'
        artifact: '${{parameters.appType}}App'
    
    