parameters:
  - name: 'appType'
    displayName: 'Application Type'
    type: string
    values:
      - Services
      - Web
  - name: 'projectNameForBuildAndDeploy'
    displayName: 'Project Name'
    type: string
    values:
      - NavaIT.Dictionary.App
      - NavaIT.Dictionary.Web

stages:
  - template: 'build.yaml'
    parameters:
      buildConfiguration: 'Release'
      projectName: '**/${{parameters.projectNameForBuildAndDeploy}}.csproj'
      artifact: '${{parameters.appType}}App'
  - stage: 'MainStageDeploy${{replace(parameters.projectNameForBuildAndDeploy, ''.'', ''_'')}}'
    displayName: 'Deploy ${{parameters.projectNameForBuildAndDeploy}}'
    jobs:
    - template: 'deploy.yaml'
      parameters:
        appType: ${{parameters.appType}}
        buildConfiguration: 'Release'
        projectName: '**/${{parameters.projectNameForBuildAndDeploy}}.csproj'
        artifact: '${{parameters.appType}}App'
    
    