parameters:
  - name: 'buildConfiguration'
    displayName: 'Build Configuration'
    type: string
    values:
      - Release
      - Debug
  - name: 'projectName'
    displayName: 'Project Name'
    type: string
  - name: 'artifact'
    displayName: 'Artifact Name'
    type: string

stages:
  - stage: Build${{replace(parameters.projectName, '.', '_')}}
    displayName: 'Build ${{parameters.projectName}}'
    jobs:
      - job: 'Build'
        displayName: 'Build ${{parameters.projectName}}'
        pool:
          name: $(buildServer)
        
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore the project - ${{parameters.buildConfiguration}}'
            inputs:
              command: 'restore'
              projects: '**/${{parameters.projectName}}.csproj'
          
          - task: DotNetCoreCLI@2
            displayName: 'Build the project - ${{parameters.buildConfiguration}}'
            inputs:
              command: 'build'
              arguments: '--configuration ${{parameters.buildConfiguration}}'
              projects: '**/${{parameters.projectName}}.csproj'
          
          - task: DotNetCoreCLI@2
            displayName: 'Publish the project - ${{parameters.buildConfiguration}}'
            inputs:
              command: 'publish'
              projects: '**/${{parameters.projectName}}.csproj'
              publishWebProjects: false
              arguments: '--no-build --configuration ${{parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)/${{parameters.projectName}}/${{parameters.buildConfiguration}}'
              zipAfterPublish: true
          
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/${{parameters.projectName}}/$(Build.SourceBranchName)'
              artifactName: ${{parameters.artifact}}
