parameters:
  - name: 'buildConfiguration'
    displayName: 'Build Configuration'
    type: string
    values:
      - Release
      - Debug
  - name: 'projectName'
    displayName: 'Project Name'
    type: string
  - name: 'artifact'
    displayName: 'Artifact Name'
    type: string
  - name: 'appType'
    displayName: 'Application Type'
    type: string
  - name: 'portNumber'
    type: string

jobs:
  - deployment: 'Deploy${{replace(parameters.projectName, ''.'', ''_'')}}'
    displayName: 'Deploy ${{parameters.projectName}}'
    environment: $(deployEnviroment)
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo $(System.ArtifactsDirectory)
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              artifactName: ${{parameters.artifact}}
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'IIS Web App Manage'
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'Sandbox${{parameters.appType}}'
              WebsitePhysicalPath: '%SystemDrive%\sandbox\${{parameters.appType}}\$(Build.SourceBranchName)'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"${{parameters.portNumber}}","hostname":"","sslThumbprint":"","sniFlag":false}]}'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'Sandbox${{parameters.appType}}'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolName: 'Sandbox${{parameters.appType}}_$(build.SourceBranchName)'
              AppPoolIdentityForWebsite: 'SpecificUser'
              AppPoolUsernameForWebsite: '$(iisUsername)'
              AppPoolPasswordForWebsite: '$(iisUserPassword)'
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'IIS Web App Deploy'
            inputs:
              WebSiteName: 'Sandbox${{parameters.appType}}'
              VirtualApplication: '/$(Build.SourceBranchName)'
              Package: '$(System.DefaultWorkingDirectory)\**\*.zip'
              RemoveAdditionalFilesFlag: true
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true
