parameters:
  - name: 'buildConfiguration'
    displayName: 'Build Configuration'
    type: string
    values:
      - Release
      - Debug
  - name: 'projectName'
    displayName: 'Project Name'
    type: string
  - name: 'artifact'
    displayName: 'Artifact Name'
    type: string
  - name: 'appType'
    displayName: 'Application Type'
    type: string
  - name: 'portNumber'
    type: string

jobs:
  - deployment: 'Deploy${{replace(parameters.projectName, ''.'', ''_'')}}'
    displayName: 'Deploy ${{parameters.projectName}}'
    environment: $(deployEnviroment)
    variables:
      - name: branchNameWithoutRefs 
        value: ${{ replace(variables['Build.SourceBranch'], 'refs/', '') }}
      - name: branchNameToTileCase
        value: ${{ variables['Build.SourceBranch'] }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: InstallNetCoreRuntimeAndHosting@1
            inputs:
              version: '5.0'
              useProxy: false
              norestart: true
              iisReset: true
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                  $branch = '$(branchNameToTileCase)' -replace 'refs/(heads/)?(.*)','$2'
                  Write-Host "##vso[task.setvariable variable=branchNameWithoutRefs]$branch"
                  $branch = (Get-Culture).TextInfo.ToTitleCase('$(branchNameToTileCase)' ) -replace 'refs/(heads/)?(.*)','$2' -replace '/',''
                  Write-Host "##vso[task.setvariable variable=branchNameToTileCase]$branch"
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              artifactName: ${{parameters.artifact}}
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'IIS Web App Manage'
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'Sandbox${{parameters.appType}}'
              WebsitePhysicalPath: '%SystemDrive%\sandbox\${{parameters.appType}}'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"${{parameters.portNumber}}","hostname":"test.apll.ir","sslThumbprint":"","sniFlag":false}]}'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'Sandbox${{parameters.appType}}'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolName: 'Sandbox${{parameters.appType}}'
              AppPoolIdentityForWebsite: 'SpecificUser'
              AppPoolUsernameForWebsite: '$(iisUsername)'
              AppPoolPasswordForWebsite: '$(iisUserPassword)'
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebApplication'
              ParentWebsiteNameForApplication: 'Sandbox${{parameters.appType}}'
              VirtualPathForApplication: '/$(branchNameWithoutRefs)'
              PhysicalPathForApplication: '%SystemDrive%\sandbox\${{parameters.appType}}\$(branchNameWithoutRefs)'
              ApplicationPhysicalPathAuth: 'ApplicationWindowsAuth'
              ApplicationAuthUserName: '$(iisUsername)'
              ApplicationAuthUserPassword: '$(iisUserPassword)'
              CreateOrUpdateAppPoolForApplication: true
              AppPoolNameForApplication: 'Sandbox${{parameters.appType}}_$(branchNameToTileCase)'
              DotNetVersionForApplication: 'No Managed Code'
              PipeLineModeForApplication: 'Integrated'
              AppPoolIdentityForApplication: 'SpecificUser'
              AppPoolUsernameForApplication: '$(iisUsername)'
              AppPoolPasswordForApplication: '$(iisUserPassword)'
          - script: 'echo $(System.ArtifactsDirectory)\**\${{parameters.projectName}}.zip'
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'IIS Web App Deploy'
            inputs:
              WebSiteName: 'Sandbox${{parameters.appType}}'
              VirtualApplication: '/$(branchNameWithoutRefs)'
              Package: '$(System.ArtifactsDirectory)\**\${{parameters.projectName}}.zip'
              RemoveAdditionalFilesFlag: true
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true
