stages:
  - stage: PrepareVariables
    displayName: Prepare Variables
    jobs:
      - job: 'PrepareVariable'
        pool:
          name: $(buildServer)
        variables:
          - name: branchNameWithoutRefs 
            value: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/', ''), 'head/', '') }}
          - name: branchNameToPhysicalPath 
            value: ${{ replace(variables['branchNameWithoutRefs'], '/', '\') }}
          - name: branchNameToTileCase
            value: ${{ variables['Build.SourceBranch'] }}
          - name: isAspDotNetCoreInstalled
            value: false
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |-
                  $branch = (Get-Culture).TextInfo.ToTitleCase('$(branchNameToTileCase)' ) -replace 'refs/(heads/)?(.*)','$2' -replace '/',''
                  Write-Host "##vso[task.setvariable variable=branchNameToTileCase]$branch"
          - script: 'echo branchNameWithoutRefs -- $(branchNameWithoutRefs )'
          - script: 'echo branchNameToPhysicalPath -- $(branchNameToPhysicalPath )'
          - script: 'echo branchNameToTileCase-- $(branchNameToTileCase)'
          - script: 'echo isAspDotNetCoreInstalled-- $(isAspDotNetCoreInstalled)'


