# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  name: 'Windows Agent Poll'

variables:
  buildConfiguration: 'Release'

steps:
- template: pipeline-template/build.yaml
  parameters:
    buildConfiguration: 'Release'
    buildProject: 'NavaIT.Dictionary.App.csproj'
    artifact: '$(Build.SourceBranchName)-serviceApp-Sandbox'
- template: pipeline-template/build.yaml
  parameters:
    buildConfiguration: 'Release'
    buildProject: 'NavaIT.Dictionary.Web.csproj'
    artifact: '$(Build.SourceBranchName)-web-Sandbox'
