# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature/EnablingSSR

pool:
  name: 'Windows Agent Poll'

variables:
  buildConfiguration: 'Release'
  buildProject: '**/NavaIT.Dictionary.App.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore the project - $(buildConfiguration)'
  inputs:
    command: 'restore'
    projects: '$(buildProject)'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(buildProject)'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '$(buildProject)'
    publishWebProjects: false
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    zipAfterPublish: true

- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: serviceApp
